# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddBookListForm.ui'
#
# Created: Wed Jul  3 17:00:46 2019
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddBookList(object):
    def setupUi(self, AddBookList):
        AddBookList.setObjectName("AddBookList")
        AddBookList.resize(1096, 740)
        self.layoutWidget = QtWidgets.QWidget(AddBookList)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 20, 1031, 651))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.AddBookListProgressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.AddBookListProgressBar.setProperty("value", 0)
        self.AddBookListProgressBar.setObjectName("AddBookListProgressBar")
        self.horizontalLayout_2.addWidget(self.AddBookListProgressBar)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.AllListNumLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.AllListNumLineEdit.setEnabled(False)
        self.AllListNumLineEdit.setObjectName("AllListNumLineEdit")
        self.verticalLayout_6.addWidget(self.AllListNumLineEdit)
        self.AvailableListNumlineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.AvailableListNumlineEdit.setEnabled(False)
        self.AvailableListNumlineEdit.setObjectName("AvailableListNumlineEdit")
        self.verticalLayout_6.addWidget(self.AvailableListNumlineEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.AddSuccessNumLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.AddSuccessNumLineEdit.setEnabled(False)
        self.AddSuccessNumLineEdit.setObjectName("AddSuccessNumLineEdit")
        self.verticalLayout_8.addWidget(self.AddSuccessNumLineEdit)
        self.AddFailureNumLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.AddFailureNumLineEdit.setEnabled(False)
        self.AddFailureNumLineEdit.setObjectName("AddFailureNumLineEdit")
        self.verticalLayout_8.addWidget(self.AddFailureNumLineEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout_10, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ShowPDFUrlLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.ShowPDFUrlLineEdit.setEnabled(True)
        self.ShowPDFUrlLineEdit.setMinimumSize(QtCore.QSize(500, 33))
        self.ShowPDFUrlLineEdit.setObjectName("ShowPDFUrlLineEdit")
        self.verticalLayout_2.addWidget(self.ShowPDFUrlLineEdit)
        self.ShowBookListUrlLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.ShowBookListUrlLineEdit.setMinimumSize(QtCore.QSize(0, 33))
        self.ShowBookListUrlLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ShowBookListUrlLineEdit.setObjectName("ShowBookListUrlLineEdit")
        self.verticalLayout_2.addWidget(self.ShowBookListUrlLineEdit)
        self.ShowSavePDFUrlLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.ShowSavePDFUrlLineEdit.setMinimumSize(QtCore.QSize(0, 33))
        self.ShowSavePDFUrlLineEdit.setObjectName("ShowSavePDFUrlLineEdit")
        self.verticalLayout_2.addWidget(self.ShowSavePDFUrlLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.AddPDFButton = QtWidgets.QPushButton(self.layoutWidget)
        self.AddPDFButton.setObjectName("AddPDFButton")
        self.verticalLayout_3.addWidget(self.AddPDFButton)
        self.AddBookListButton = QtWidgets.QPushButton(self.layoutWidget)
        self.AddBookListButton.setObjectName("AddBookListButton")
        self.verticalLayout_3.addWidget(self.AddBookListButton)
        self.SavePDFButton = QtWidgets.QPushButton(self.layoutWidget)
        self.SavePDFButton.setObjectName("SavePDFButton")
        self.verticalLayout_3.addWidget(self.SavePDFButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.RunButton = QtWidgets.QPushButton(self.layoutWidget)
        self.RunButton.setEnabled(True)
        self.RunButton.setMinimumSize(QtCore.QSize(0, 130))
        self.RunButton.setAutoDefault(False)
        self.RunButton.setObjectName("RunButton")
        self.horizontalLayout.addWidget(self.RunButton, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.ShowInformationTextEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.ShowInformationTextEdit.setObjectName("ShowInformationTextEdit")
        self.gridLayout.addWidget(self.ShowInformationTextEdit, 7, 0, 2, 1)

        self.retranslateUi(AddBookList)
        QtCore.QMetaObject.connectSlotsByName(AddBookList)

    def retranslateUi(self, AddBookList):
        _translate = QtCore.QCoreApplication.translate
        AddBookList.setWindowTitle(_translate("AddBookList", "PDF目录添加工具"))
        self.label_4.setText(_translate("AddBookList", "目录添加进度:"))
        self.label_5.setText(_translate("AddBookList", "目录基本信息:"))
        self.label_6.setText(_translate("AddBookList", "目录条目总数:"))
        self.label_7.setText(_translate("AddBookList", "有效条目总数:"))
        self.label_8.setText(_translate("AddBookList", "成功添加数量:"))
        self.label_9.setText(_translate("AddBookList", "添加失败数量:"))
        self.label.setText(_translate("AddBookList", "PDF路径:"))
        self.label_2.setText(_translate("AddBookList", "所选目录:"))
        self.label_3.setText(_translate("AddBookList", "新PDF保存路径:"))
        self.AddPDFButton.setText(_translate("AddBookList", "加载PDF"))
        self.AddBookListButton.setText(_translate("AddBookList", "加载目录列表"))
        self.SavePDFButton.setText(_translate("AddBookList", "输入PDF新名称"))
        self.RunButton.setText(_translate("AddBookList", "执行程序"))
        self.label_10.setText(_translate("AddBookList", "信息打印:"))
        self.label_11.setText(_translate("AddBookList", "功能操作:"))

